// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":    "src-99785848cecbb326",
		"oceanbase":  "src-3e0a7e0e0ab0b619",
		"diros":      "src-3d09d05982abf8cf",
		"sphinx":     "src-85601aaa25456cf1",
		"sqlserver":  "src-703a625726deff98",
		"sqlite":     "src-7d841dda22330f67",
		"duckdb":     "src-6d3b9eefc9802162",
		"dameng":     "src-8a758078ab1fd981",
		"kingbase":   "src-0086ac3cb15dd34d",
		"highgo":     "src-147aec3df7ef7461",
		"vastbase":   "src-cb0a4f1e6633f810",
		"opengauss":  "src-f9924897702b760d",
		"mongodb":    "src-a4eab8b91194dc18",
		"tdengine":   "src-f43c25ea8b55d81f",
		"clickhouse": "src-c24f610c0f65228f",
	}
}
