// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":    "src-d6c5c6717338834c",
		"diros":      "src-ed4f0f64ed28d3fa",
		"sphinx":     "src-f52324f0a812d7c8",
		"sqlserver":  "src-ec165f18de9cd8b3",
		"sqlite":     "src-9dea6c76bc931114",
		"duckdb":     "src-14027ac1de3c50c7",
		"dameng":     "src-1a08880ff5bbcf31",
		"kingbase":   "src-28eed0e4d942b724",
		"highgo":     "src-76146bf97f07f25c",
		"vastbase":   "src-555b60c4863542b6",
		"mongodb":    "src-2540a7350c4243aa",
		"tdengine":   "src-ce3e4a9c46f6b92d",
		"clickhouse": "src-78e5ada4da56704d",
	}
}
